name: Thau React

on:
  push:
    branches: 
      - master
    paths:
      - '**/*.ts'
      - '**/*.json'
      - '**/*.js'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 14.4.0
    - name: Test Thau React
      run: |
        yarn
        yarn lint
        yarn test

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 14.4.0
    - name: Build and Push the Thau React package
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > .npmrc
        yarn
        yarn build
        git config --global user.email "mr6r1n@gmail.com"
        git config --global user.name "Github CI"
        yarn version --patch
        npm publish